# Generated by Django 3.2.4 on 2021-07-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0005_auto_20210715_2021'),
        ('accounts', '0003_alter_healthofficer_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('reporting_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.healthofficer')),
            ],
        ),
    ]
