# Generated by Django 3.2.4 on 2021-06-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBio',
            fields=[
                ('huduma_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'patientbio',
                'db_table': 'patientbio',
                'ordering': ('dob',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presententing_symptoms', models.TextField()),
                ('lab_works', models.TextField()),
                ('diagnosis_made', models.TextField()),
                ('treatment', models.TextField()),
                ('comment', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('health_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.healthofficer')),
            ],
            options={
                'verbose_name_plural': 'patientinfo',
                'db_table': 'patientinfo',
                'ordering': ('date',),
            },
        ),
    ]
