# Generated by Django 3.2.4 on 2021-06-23 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20210620_0008'),
        ('patient', '0002_patientbio_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='treatment',
            new_name='treatment_offered',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='patient.patientbio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='x_ray',
            field=models.ImageField(blank=True, help_text="Patient's Profile Pic", upload_to='media/patients/x_rays/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='patientbio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patientbio',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientbio',
            name='pic',
            field=models.ImageField(blank=True, help_text="Patient's Profile Pic", upload_to='media/patients/profile_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='The Date this Record was made'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='patientbio',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita Taveta', 'Taita Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], max_length=50),
        ),
    ]
