# Generated by Django 3.2.4 on 2021-06-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210623_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='presententing_symptoms',
            new_name='presenting_symptoms',
        ),
    ]
