# Generated by Django 3.2.4 on 2021-07-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_presententing_symptoms_patient_presenting_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbio',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='patientbio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientbio',
            name='location',
        ),
        migrations.RemoveField(
            model_name='patientbio',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='patientbio',
            name='pic',
        ),
        migrations.AlterField(
            model_name='patientbio',
            name='phone',
            field=models.CharField(help_text='for infants, enter gurdians/parents phone', max_length=10),
        ),
    ]
