# Generated by Django 3.2.4 on 2021-07-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210715_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='docs',
            field=models.FileField(blank=True, help_text="Patient's Profile Pic", upload_to='media/patients/treatment documents/%Y/%m/%d'),
        ),
    ]
