# Generated by Django 3.2.4 on 2021-06-19 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthOfficer',
            fields=[
                ('id_number', models.CharField(max_length=10)),
                ('reg_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'health_officers',
                'db_table': 'health_officers',
                'ordering': ('reg_number',),
            },
        ),
    ]
