# Generated by Django 3.2.4 on 2021-06-23 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthofficer',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthofficer',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthofficer',
            name='pic',
            field=models.ImageField(blank=True, help_text='Health officers Profile Pic', upload_to='media/officers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='healthofficer',
            name='title',
            field=models.CharField(choices=[('Medical Oficer', 'Medical Officer'), ('Consultant', 'Consultant'), ('Surgeon', 'Surgeon'), ('Neural Surgeon', 'Neural Surgeon'), ('Gynaecologist', 'Gynaecologist'), ('ENT Expert', 'ENT Expert'), ('Paediatric', 'Paediatric'), ('Psychiatrist', 'Psychiatrist'), ('Clinical Officer', 'Officer'), ('Cardiologist', 'Cardiologist'), ('Other', 'Other')], max_length=100),
        ),
    ]
