# Generated by Django 3.2.4 on 2021-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20210620_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_level',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6')], default='Level 1', max_length=50),
        ),
    ]
