# Generated by Django 3.2.4 on 2021-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_facility_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
    ]
